version: "3.3"
services:
  webserverservice:
    image: letlojanesg/wonderlabs:wonderlabs-apache
    deploy:
      replicas: 2
      mode: replicated
      endpoint_mode: dnsrr
    networks:
      - overlay
     
  loadbalancerservice:
    image: letlojanesg/wonderlabs:wonderlabs-haproxy
    ports:
      - "80:80"
      - "1991:1991"
    depends_on:
      - webserverservice
    networks:
      - overlay
networks:
  overlay:
